pipeline_settings:
  output_directory: "~/output_genomics_pipeline"

reference_genome:
  grch37: "TOBEDONE"
  grch38: "/kuttam_fg/refdata/robin/references/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta"

gatk_ressources:
  known_sites:
    dbsnp: "/kuttam_fg/refdata/robin/references/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz"
    omni1000: "/kuttam_fg/refdata/robin/references/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/1000G_omni2.5.hg38.vcf.gz"
    mills_indels: "/kuttam_fg/refdata/robin/references/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"

exomes_kits:
  grch38:
    sureselectv6: "/kuttam_fg/refdata/robin/references/exome_kits/grch38/S07604514_hg38/S07604514_Covered.bed"
    nextera: "/kuttam_fg/refdata/robin/references/exome_kits/grch38/nextera_targets.hg38.lifted.bed"
    
modules_resources:
  module:
    alignment:
      cpus: 32
      mem: 30
    fixmate:
      cpus: 16
      mem: 60
    markduplicates:
      cpus: 20
      mem: 60
    intervalsBQSR:
      cpus: 2
      mem: 4
    applyBQSR:
      cpus: 2
      mem: 8
    filterBAM:
      cpus: 16
      mem: 32
    hc:
      cpus: 2
      mem: 8
    bamqc:
      cpus: 4
      mem: 16